### ISSUE TITLE
how do we start the server?

### ISSUE THREAD

**Issue by hazeezet** [dconco/php_slides#26]

**Comment by kigemmanuel** [comment]
**PhpSlides** works together with any PHP server. Like xampp, so it doesn't has its own server... Run xampp server where the slides project is been created then follow the localhost link on the browser, that's all, you've runned the project. Also if the slides project is ready to be hosted, you can host it as you host normal PHP hosting

**Comment by hazeezet** [comment]
Where is the entry point

As far as I know, there is always an index file where it is. Or am I missing something?

**Comment by kigemmanuel** [comment]
Just tell him this first.
"It's working with routes in the `routes` directory, and there's no `index.php` in the root directory of the project

**Comment by kigemmanuel** [comment]
"After you've run the project on a server, follow the URL, can be http://localhost:8080 it'll show the default dashboard page as the main page which is registered in the `route.php` file inside the `route` folder in the root of the project... Can register new routes too. 
You can read the documentation in the `README.md` file for more details"

**Comment by hazeezet** [comment]
Which command? That is exactly what I'm asking, how to run.

Kindly add how to in the readme. 

To run any server, you need an entry point, where is it?.

Or kindly show on a video

**Comment by kigemmanuel** [comment]
It's working with routes in the `routes` directory, and there's no `index.php` in the root directory of the project

**Comment by daveconco** [comment]
> "After you've run the project on a server, follow the URL, can be http://localhost:8080 it'll show the default dashboard page as the main page which is registered in the `route.php` file inside the `route` folder in the root of the project... Can register new routes too. You can read the documentation in the `README.md` file for more details"

**Comment by daveconco** [comment]
@hazeezet The command you're talking about...

Create a project with this command with your terminal in any directory you want

`composer create-project dconco/php_slides project-name`

Or instead download the released version from GitHub or clone the project directly 

Then move directory to the project name on terminal 

`cd project-name`

And run 
`composer install`

But make sure you've composer already installed on your terminal

Then use your PHP server to start the project using Apache and follow the localhost then you'll see the dashboard

**Comment by hazeezet** [comment]
I have issues running it that's why I ask. I have everything. I need an entry point of the application

If I run the folder through xampp, the page that will show is just listing the files.

Where is the index file or an entry point of the application 

That is what I'm asking

**Comment by hazeezet** [comment]
Kindly provide a working video

Thank you
